### ISSUE TITLE
`passimd` keeps file content in memory upon startup

### ISSUE THREAD

**Issue by mgerstner** [hughsie/passim#24]
I observed that the daemon behaves inconsistenly regarding keeping the cached files' content in memory. When initially publishing a file, the file's data will be freed again from memory:

```
# dd if=/dev/random bs=4096 count=250000 >large.bin
# passim publish large.bin
Published: d86a2d3ac4a0188f530e954aa09ced682cc6ac525ee94be1245c18d1ad9a6bf2 large.bin age:84/86400 share:0/5 size:1
.0 GB
# ps -o command,%mem ax | grep passim
/usr/libexec/passimd         0.1
```

When restarting the service, however, the daemon will keep the data of the already published file in memory:

```
# systemctl restart passimd.service
# ps -o command,%mem ax | grep passimd
/usr/libexec/passimd        50.6
```

Looking at the code it seems the in-memory cached data is practically never used. `passim_item_get_bytes()` is only called in [passim-client.c](https://github.com/hughsie/passim/blob/main/libpassim/passim-client.c#L335) and also only if there is no file object assigned to the item. Can this even ever happen? It's not called in the daemon's context anyway.

Keeping the cached file's content in memory might make sense for small files, up to some maximum per-process memory limit, but likely not for large files. In any case the behaviour should be consistent between files added during runtime and during startup of the daemon IMHO.

**Comment by hughsie** [comment]
@mgerstner thanks for all the super-well reported bugs -- it's much appreciated!

**Comment by mgerstner** [comment]
I verified this fix.
