### ISSUE TITLE
EL 9 Support

### ISSUE THREAD

**Issue by timway** [hughsie/passim#3]
```bash
quay.io/centos/centos:stream9
dnf --assumeyes install 'dnf-command(config-manager)'
dnf config-manager --set-enabled crb
dnf --assumeyes install cmake diffutils gcc git glib2-devel gobject-introspection-devel meson systemd
```

```bash
Dependency gio-unix-2.0 found: NO found 2.68.4 but need: '>= 2.76.0'
```

It appears `meson` isn't configured to handle how `gio-unix-2.0` is handled in versions of `gobject-introspection-devel` prior to 2.76.0. I'm not sure of the syntax in meson that would allow earlier versions with the included sub-folder for `gio-unix-2.0` and still allow newer versions. It does compile on Fedora 38 no problem.

**Comment by hughsie** [comment]
> It appears meson isn't configured to handle how gio-unix-2.0 is handled

I think it's simpler than that; I'm using symbols from glib2 2.76.0 and RHEL 9 only has glib2 2.68.4.

**Comment by hughsie** [comment]
If you change meson.build to be 2.68.4 and then tell me what the compile errors are then we can make a call on how much compat code would be needed.

**Comment by timway** [comment]
@hughsie I know the issue is closed but I can confirm it now compiles without issue on CentOS Stream 9 running on aarch64. Thanks!
