### ISSUE TITLE
Have you considered reaching out to the containers group?

### ISSUE THREAD

**Issue by ericcurtin** [hughsie/passim#30]
People like @rhatdan ? etc.

Some artefacts are listed here like:

- AdBlocker metadata
- Firmware update metadata
- Remote metadata for update frameworks, e.g. apt-get/dnf

But some really meaty artefacts that could really benefit from this are OCI images in a data-centre, to put less reliance on centralized OCI registries.

There are some solutions out there that do this:

https://github.com/uber/kraken

but I think passim could be a nice opinionated one for all solution for rpms, OCI images (which are a huge family of different artefacts in itself like bootable containers). Could be a great solution for many different artefacts in Fedora, I think OCI images could potentially benefit the most because their scope in large and hence OCI images get large.

**Comment by ericcurtin** [comment]
Nevermind I see there is awareness of this from #11

**Comment by hughsie** [comment]
Yes, I think this is a valid usecase too. I did really want this included in Fedora 40 and used *in anger* a bit before trying to support more usecases. If the F40 rollout goes smoothly I think it's worth talking to other groups and getting some additional input. I think it's important to be a zero-configuration feature to be useful, and that sure makes it _divisive_.

**Comment by ericcurtin** [comment]
We are looking for ways to cut down on bandwidth costs in IoT as I sent in email, specifically in Automotive, much harder problem because of issues like this you highlighted at a global network scale:

"ITAR/EAR legal considerations"

but it's something I have in the back of my mind as the concern is there.

**Comment by ericcurtin** [comment]
> divisive

Ah well... Configurable on or off solves this right :smile:

**Comment by hughsie** [comment]
> ITAR/EAR legal considerations

This is actually pretty good at solving "this should never leave the site" use-cases too -- if mDNS/Passim port is blocked on the firewall then the image can't escape.

**Comment by ericcurtin** [comment]
> > divisive
> 
> Ah well... Configurable on or off solves this right 😄
> 
> Like it/don't like it install/uninstall, configure, etc.

And I know what you mean by zero-configuration, it should just be able to find other hosts :)

I mean turn it on/off

**Comment by ericcurtin** [comment]
One usecase where passim could be, is local within a device itself, this seems silly at first but there are use-cases where this makes sense. Here is one I just encountered. I just ran a rootless "podman run", after waiting ~20 minutes for the pull, the container ran, once it ran, I realised rootless wasn't enough privileges, so I had to do "sudo podman run", now I'm waiting another 20 minutes on a slow connection I'm currently on.

While it might not necessarily make sense to share rootful and rootless by default. I think it does make sense if a tool like passim realised that we need not download the whole container image again on the internet.

**Comment by hughsie** [comment]
> after waiting ~20 minutes for the pull

Is the "container" one big blob on disk or bazillions of tiny files? Passim is really optimised for the "few big blob" usecases.

**Comment by ericcurtin** [comment]
> > after waiting ~20 minutes for the pull
> 
> Is the "container" one big blob on disk or bazillions of tiny files? Passim is really optimised for the "few big blob" usecases.

It depends I guess 😅

**Comment by ericcurtin** [comment]
> > > after waiting ~20 minutes for the pull
> > 
> > 
> > Is the "container" one big blob on disk or bazillions of tiny files? Passim is really optimised for the "few big blob" usecases.
> 
> It depends I guess 😅

I don't think podman pulls, etc. ever pull bazillions of layers at once it's seems to pull like 3 max at once, but I don't know the lower level details.
